services:
  ha:
    build: .
    stdin_open: true
    tty: true
    cap_add:
      - ALL
    privileged: true    
    networks:
      net10:
        ipv4_address: 10.0.10.3

  hb:
    build: .
    stdin_open: true
    tty: true
    cap_add:
      - ALL
    privileged: true    
    networks:
      net11:
        ipv4_address: 10.0.11.3

  r1:
    build: .
    stdin_open: true
    tty: true
    cap_add:
      - ALL
    privileged: true
    networks:
      net10:
        ipv4_address: 10.0.10.4
      net12:
        ipv4_address: 10.0.12.1
      net13:
        ipv4_address: 10.0.13.1

  r2:
    build: .
    stdin_open: true
    tty: true
    cap_add:
      - ALL
    privileged: true
    networks:
      net12:
        ipv4_address: 10.0.12.2
      net14:
        ipv4_address: 10.0.14.2

  r3:
    build: .
    stdin_open: true
    tty: true
    cap_add:
      - ALL
    privileged: true
    networks:
      net14:
        ipv4_address: 10.0.14.3
      net11:
        ipv4_address: 10.0.11.4
      net15:
        ipv4_address: 10.0.15.3

  r4:
    build: .
    stdin_open: true
    tty: true
    cap_add:
      - ALL
    privileged: true
    networks:
      net13:
        ipv4_address: 10.0.13.4
      net15:
        ipv4_address: 10.0.15.4

networks:
  net10:
    ipam:
      config:
        - subnet: 10.0.10.0/24

  net11:
    ipam:
      config:
        - subnet: 10.0.11.0/24

  net12:
    ipam:
      config:
        - subnet: 10.0.12.0/24

  net13:
    ipam:
      config:
        - subnet: 10.0.13.0/24

  net14:
    ipam:
      config:
        - subnet: 10.0.14.0/24

  net15:
    ipam:
      config:
        - subnet: 10.0.15.0/24
