services:
  ha:
    build: .
    stdin_open: true
    tty: true
    cap_add:
      - ALL
    privileged: true    
    networks:
      net114:
        ipv4_address: 10.0.114.3

  hb:
    build: .
    stdin_open: true
    tty: true
    cap_add:
      - ALL
    privileged: true    
    networks:
      net134:
        ipv4_address: 10.0.134.3

  r1:
    build: .
    stdin_open: true
    tty: true
    cap_add:
      - ALL
    privileged: true
    networks:
      net114:
        ipv4_address: 10.0.114.4
      net112:
        ipv4_address: 10.0.112.1
      net141:
        ipv4_address: 10.0.141.1

  r2:
    build: .
    stdin_open: true
    tty: true
    cap_add:
      - ALL
    privileged: true
    networks:
      net112:
        ipv4_address: 10.0.112.2
      net123:
        ipv4_address: 10.0.123.2

  r3:
    build: .
    stdin_open: true
    tty: true
    cap_add:
      - ALL
    privileged: true
    networks:
      net123:
        ipv4_address: 10.0.123.3
      net134:
        ipv4_address: 10.0.134.4
      net143:
        ipv4_address: 10.0.143.3

  r4:
    build: .
    stdin_open: true
    tty: true
    cap_add:
      - ALL
    privileged: true
    networks:
      net141:
        ipv4_address: 10.0.141.4
      net143:
        ipv4_address: 10.0.143.4

networks:
  net114:
    ipam:
      config:
        - subnet: 10.0.114.0/24

  net134:
    ipam:
      config:
        - subnet: 10.0.134.0/24

  net112:
    ipam:
      config:
        - subnet: 10.0.112.0/24

  net123:
    ipam:
      config:
        - subnet: 10.0.123.0/24

  net141:
    ipam:
      config:
        - subnet: 10.0.141.0/24

  net143:
    ipam:
      config:
        - subnet: 10.0.143.0/24
