version: "3.8"

services:
  ha:
    build: .
    stdin_open: true
    tty: true
    cap_add:
      - ALL
    privileged: true    
    networks:
      net14:
        ipv4_address: 10.0.14.3

  hb:
    build: .
    stdin_open: true
    tty: true
    cap_add:
      - ALL
    privileged: true    
    networks:
      net15:
        ipv4_address: 10.0.15.3

  r1:
    build: .
    stdin_open: true
    tty: true
    cap_add:
      - ALL
    privileged: true
    networks:
      net14:
        ipv4_address: 10.0.14.4
      net16:
        ipv4_address: 10.0.16.1
      net18:
        ipv4_address: 10.0.18.1

  r2:
    build: .
    stdin_open: true
    tty: true
    cap_add:
      - ALL
    privileged: true
    networks:
      net16:
        ipv4_address: 10.0.16.2
      net17:
        ipv4_address: 10.0.17.2

  r3:
    build: .
    stdin_open: true
    tty: true
    cap_add:
      - ALL
    privileged: true
    networks:
      net17:
        ipv4_address: 10.0.17.3
      net15:
        ipv4_address: 10.0.15.4
      net19:
        ipv4_address: 10.0.19.3

  r4:
    build: .
    stdin_open: true
    tty: true
    cap_add:
      - ALL
    privileged: true
    networks:
      net18:
        ipv4_address: 10.0.18.4
      net19:
        ipv4_address: 10.0.19.4

networks:
  net14:
    ipam:
      config:
        - subnet: 10.0.14.0/24

  net15:
    ipam:
      config:
        - subnet: 10.0.15.0/24

  net16:
    ipam:
      config:
        - subnet: 10.0.16.0/24

  net17:
    ipam:
      config:
        - subnet: 10.0.17.0/24

  net18:
    ipam:
      config:
        - subnet: 10.0.18.0/24

  net19:
    ipam:
      config:
        - subnet: 10.0.19.0/24
