FROM jrei/systemd-ubuntu

RUN apt-get update && \
    apt-get -y install bash iproute2 net-tools tcpdump vim iputils-ping python3-pip telnet && \
    apt-get clean

RUN pip3 install pexpect --break-system-packages

COPY ./frrsetup /root/frrsetup
RUN chmod +x /root/frrsetup && /root/frrsetup

COPY ./daemons /etc/frr/daemons 
COPY ./r2_frr.conf /etc/frr/frr.conf
COPY ./frrrestart /root 
COPY ./setospf.py /root 

CMD ["bash"]
