#!/bin/bash

set -e

apt-get update
apt-get -y install curl gnupg lsb-release

curl -s https://deb.frrouting.org/frr/keys.gpg | tee /usr/share/keyrings/frrouting.gpg > /dev/null

FRRVER="frr-stable"
echo "deb [signed-by=/usr/share/keyrings/frrouting.gpg] https://deb.frrouting.org/frr $(lsb_release -s -c) $FRRVER" \
    | tee /etc/apt/sources.list.d/frr.list

apt-get update && apt-get -y install frr frr-pythontools
