#!/bin/bash

# Install prerequisites
apt -y update
apt -y install curl gnupg 

# Add FRR repository and install FRR
curl -s https://deb.frrouting.org/frr/keys.gpg | \
  tee /usr/share/keyrings/frrouting.gpg > /dev/null

curl -s https://deb.frrouting.org/frr/keys.gpg | tee /usr/share/keyrings/frrouting.gpg > /dev/null

echo "deb [signed-by=/usr/share/keyrings/frrouting.gpg] https://deb.frrouting.org/frr $(lsb_release -s -c) frr-stable" \
  | tee /etc/apt/sources.list.d/frr.list
apt update && apt -y install frr frr-pythontools

# Enable OSPF
sed -i 's/ospfd=no/ospfd=yes/' /etc/frr/daemons

# Restart FRR to apply changes
echo "Restarting FRR..."
service frr restart
